# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y curl

# Copy the backend code and models
COPY src/ /app/src/
COPY serve.py /app/
COPY models/ /app/models/

# Expose port for FastAPI
EXPOSE 5058

# Start FastAPI server
CMD ["python", "serve.py"]
